language: node_js
node_js:
  - "5.11"
sudo: false
script:
  - "cd ./tests/example && npm install ../../ --save && npm install caesium-coffee --save"
  - "cd ../../ && npm test"
  - "./node_modules/.bin/mocha --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e00804dcf2c0cfb45bd6
    on_success: change
    on_failure: always
    on_start: never
