language: node_js
node_js:
  - "5.11"
sudo: false
script:
  - "npm test"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e00804dcf2c0cfb45bd6
    on_success: change
    on_failure: always
    on_start: never
